#branchVarName: CIRCLE_BRANCH
#branchVarDefault: develop

#branches:
#  - name: develop
#    suffix: _DEV
#  - name: staging
#    suffix: _STG

packages:
  - package: api
    envFile: .api.env
    variables:
      - API_ENDPOINT
      - API_TIMEOUT

  - package: api/db
    variables:
      - DB_PORT
      - DB_SCHEMA

  - package: crawler
    variables:
      - C_CRON
      - C_DB_URI

globals:
  - V_DATABASE